// Stock de productos

let stockJuegos = [

    {id: 1, nombre: "Dark souls", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "aventura"], precio: 2560, desarollador: "from software", img: '../images/juegos/dark-souls-1.jpg'},
    {id: 2, nombre: "Dark souls 2", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "aventura"], precio: 2560, desarollador: "from software", img: '../images/juegos/dark-souls-2.jpg'},
    {id: 3, nombre: "Dark souls 3", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "aventura"], precio: 6000, desarollador: "from software", img: '../images/juegos/dark-souls-3.jpg'},
    {id: 4, nombre: "Age of empires", plataforma: ["pc"], genero: ["estrategia"], precio: 1250, desarollador: "microsoft", img: '../images/juegos/age-of-empires.jpg'},
    {id: 5, nombre: "Age of empires 2", plataforma: ["pc"], genero: ["estrategia"], precio: 1250, desarollador: "microsoft", img: '../images/juegos/age-of-empires-2.jpg'},
    {id: 6, nombre: "Age of empires 3", plataforma: ["pc"], genero: ["estrategia"], precio: 1250, desarollador: "microsoft", img: '../images/juegos/age-of-empires-3.jpg'},
    {id: 7, nombre: "Bloodborne", plataforma: ["ps4"], genero: ["accion", "aventura", "terror"], precio: 1300, desarollador: "from software", img: '../images/juegos/bloodborne.jpg'},
    {id: 8, nombre: "Crash bandicoot", plataforma: ["pc", "ps4"], genero: ["plataformero", "aventura"], precio: 3200, desarollador: "naughty dog", img: '../images/juegos/crash-bandicoot.jpg'},
    {id: 9, nombre: "Crash team racing", plataforma: ["ps4"], genero: ["carreras", "infantil"], precio: 3200, desarollador: "naughty dog", img: '../images/juegos/crash-team-racing.jpg'},
    {id: 10, nombre: "Diablo 2", plataforma: ["pc"], genero: ["accion", "aventura", "terror"], precio: 600, desarollador: "blizzard", img: '../images/juegos/diablo-2.jpg'},
    {id: 11, nombre: "Diablo 3", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "aventura", "terror"], precio: 1700, desarollador: "blizzard", img: '../images/juegos/diablo-3.jpg'},
    {id: 12, nombre: "Elex", plataforma: ["pc", "ps4", "xbox"], genero: ["rpg", "aventura"], precio: 1560, desarollador: "piranha bytes", img: '../images/juegos/elex.jpg'},
    {id: 13, nombre: "Fifa 20", plataforma: ["ps4", "xbox"], genero: ["deportes", "simulador"], precio: 4560, desarollador: "electronic arts", img: '../images/juegos/fifa-20.jpg'},
    {id: 14, nombre: "Final fantasy 7", plataforma: ["ps4"], genero: ["accion", "aventura", "rpg"], precio: 4760, desarollador: "squre enix", img: '../images/juegos/final-fantasy-7.jpg'},
    {id: 15, nombre: "Final fantasy 15", plataforma: ["ps4", "xbox", "pc"], genero: ["accion", "aventura", "rpg"], precio: 4760, desarollador: "squre enix", img: '../images/juegos/final-fantasy-15.jpg'},
    {id: 16, nombre: "Guitar hero", plataforma: ["ps2"], genero: ["simulador", "musica", "infantil"], precio: 1200, desarollador: "activision", img: '../images/juegos/guitar-hero.jpg'},
    {id: 17, nombre: "Guitar hero 2", plataforma: ["ps2"], genero: ["simulador", "musica", "infantil"], precio: 1200, desarollador: "activision", img: '../images/juegos/guitar-hero-2.jpg'},
    {id: 18, nombre: "Guitar hero 3", plataforma: ["ps2"], genero: ["simulador", "musica", "infantil"], precio: 1200, desarollador: "activision", img: '../images/juegos/guitar-hero-3.jpg'},
    {id: 19, nombre: "Hades", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "aventura", "indie"], precio: 1400, desarollador: "super giant", img: '../images/juegos/hades.jpg'},
    {id: 20, nombre: "Hitman", plataforma: ["pc", "ps2"], genero: ["accion", "aventura"], precio: 860, desarollador: "io interactive", img: '../images/juegos/hitman.jpg'},
    {id: 21, nombre: "La noire", plataforma: ["pc", "ps3", "xbox"], genero: ["accion", "aventura"], precio: 1360, desarollador: "rockstar", img: '../images/juegos/la-noire.jpg'},
    {id: 22, nombre: "Left 4 dead", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "terror"], precio: 450, desarollador: "valve", img: '../images/juegos/left-4-dead.jpg'},
    {id: 23, nombre: "Left 4 dead 2", plataforma: ["pc", "ps4", "xbox"], genero: ["accion", "terror"], precio: 800, desarollador: "valve", img: '../images/juegos/left-4-dead-2.jpg'},
    {id: 24, nombre: "Lethal league", plataforma: ["pc", "ps4", "xbox"], genero: ["peleas", "indie"], precio: 1200, desarollador: "team reaptile", img: '../images/juegos/lethal-league.jpg'},
    {id: 25, nombre: "Uncharted 4", plataforma: ["ps4"], genero: ["accion", "aventura"], precio: 1800, desarollador: "naughty dog", img: '../images/juegos/uncharted-4.jpg'},
    {id: 26, nombre: "Monster hunter rise", plataforma: ["switch"], genero: ["accion", "aventura"], precio: 7000, desarollador: "capcom", img: '../images/juegos/monster-hunter-rise.jpg'},
    {id: 27, nombre: "Monster hunter world", plataforma: ["pc","ps4","xbox"], genero: ["accion", "aventura"], precio: 6000, desarollador: "capcom", img: '../images/juegos/monster-hunter-world.jpg'},
    {id: 28, nombre: "Mortal kombat 11", plataforma: ["pc", "ps4", "xbox"], genero: ["peleas", "accion"], precio: 5560, desarollador: "netherrealm studios", img: '../images/juegos/mortal-kombat-11.jpg'},
    {id: 29, nombre: "Nioh", plataforma: ["ps4", "pc"], genero: ["accion", "aventura"], precio: 600, desarollador: "team ninja", img: '../images/juegos/nioh.jpg'},
    {id: 30, nombre: "Octopath traveller", plataforma: ["nintendo", "pc"], genero: ["rpg", "aventura"], precio: 2400, desarollador: "square enix", img: '../images/juegos/octopath-traveller.jpg'},
    {id: 31, nombre: "Persona 4", plataforma: ["pc", "ps4"], genero: ["rol", "aventura"], precio: 1400, desarollador: "atlus", img: '../images/juegos/persona-4.jpg'},
    {id: 32, nombre: "Persona 5", plataforma: ["ps4", "ps5"], genero: ["rol", "aventura"], precio: 2400, desarollador: "atlus", img: '../images/juegos/persona-5.jpg'},
    {id: 33, nombre: "Pokemon ultra sol", plataforma: ["nintendo"], genero: ["accion", "aventura"], precio: 2300, desarollador: "game freak", img: '../images/juegos/pokemon-ultra-sol.jpg'},
    {id: 34, nombre: "Pokemon ultra luna", plataforma: ["nintendo"], genero: ["accion", "aventura"], precio: 1800, desarollador: "game freak", img: '../images/juegos/pokemon-ultraluna.jpg'},
    {id: 35, nombre: "Pokemon y", plataforma: ["nintendo"], genero: ["accion", "aventura"], precio: 800, desarollador: "game freak", img: '../images/juegos/pokemon-y.jpg'},
    {id: 36, nombre: "Pyre", plataforma: ["ps4", "pc", "nintendo"], genero: ["aventura"], precio: 1200, desarollador: "super giant", img: '../images/juegos/pyre.jpg'},
    {id: 37, nombre: "Resident evil 2 remake", plataforma: ["ps4", "pc", "xbox"], genero: ["accion", "terror"], precio: 1600, desarollador: "capcom", img: '../images/juegos/resident-evil-2-remake.jpg'},
    {id: 38, nombre: "Resident evil 3 remake", plataforma: ["ps4", "pc", "xbox"], genero: ["accion", "terror"], precio: 1800, desarollador: "capcom", img: '../images/juegos/resident-evil-3-remake.jpg'},
    {id: 39, nombre: "Resident evil 4", plataforma: ["ps4", "pc", "xbox", "nintendo"], genero: ["accion", "terror"], precio: 700, desarollador: "capcom", img: '../images/juegos/resident-evil-4.jpg'},
    {id: 40, nombre: "Resonance of fate", plataforma: ["ps3", "xbox", "pc"], genero: ["rpg", "aventura"], precio: 1000, desarollador: "tri ace", img: '../images/juegos/resonance-of-fate.jpg'},
    {id: 41, nombre: "Spyro", plataforma: ["ps4", "pc", "ps5"], genero: ["infantil", "aventura"], precio: 1400, desarollador: "naughty dog", img: '../images/juegos/spyro.jpg'},
    {id: 42, nombre: "Street fighter 5", plataforma: ["ps4", "xbox", "pc", "ps3"], genero: ["accion", "peleas"], precio: 2100, desarollador: "capcom", img: '../images/juegos/street-fighter-5.jpg'},
    {id: 43, nombre: "The legend of zelda", plataforma: ["nintendo"], genero: ["accion", "aventura"], precio: 2300, desarollador: "nintendo", img: '../images/juegos/the-legend-of-zelda.jpg'},
    {id: 44, nombre: "The messenger", plataforma: ["ps4", "xbox", "pc"], genero: ["accion", "aventura"], precio: 600, desarollador: "capcom", img: '../images/juegos/the-messenger.jpg'},
    {id: 45, nombre: "Ufc 4", plataforma: ["ps4", "xbox", "ps3", "pc"], genero: ["deportes", "peleas"], precio: 1500, desarollador: "electronic arts", img: '../images/juegos/ufc-4.jpg'},
    {id: 46, nombre: "Uncharted collection", plataforma: ["ps4", "ps3"], genero: ["accion", "aventura"], precio: 1400, desarollador: "naughty dog", img: '../images/juegos/uncharted-collection.jpg'},
    {id: 47, nombre: "Uncharted 4", plataforma: ["ps4"], genero: ["accion", "aventura"], precio: 1800, desarollador: "naughty dog", img: '../images/juegos/uncharted-4.jpg'},
    {id: 48, nombre: "Watch dogs", plataforma: ["ps4", "pc"], genero: ["accion", "aventura"], precio: 1800, desarollador: "ubisoft", img: '../images/juegos/watch-dogs.jpg'},
]

let stockConsolas = [

    {id: 1, nombre: ["playstation 4", "ps4", "play"], precio: 22000, compania: "sony", img: "../images/consolas/ps4.jpg"},
    {id: 2, nombre: ["nintendo", "switch", "nintentendo switch"], precio: 32000, compania: "nintendo", img: "../images/consolas/switch.jpg"},
    {id: 3, nombre: ["xbox", "x box", "one", "xbox one"], precio: 42000, compania: "microsoft", img: "../images/consolas/xbox-one.jpg"}
]
